### ISSUE TITLE
Firmware Ordner?

### ISSUE THREAD

**Issue by isjo-org** [tnn85/MPCNC-Nano-Estlcam-Shield#3]
Hallo!

lt. Readme sollte es einen Firmware Ordner mit dem Code für den Arduino geben, habe ich etwas überlesen, oder übersehen?

Mir ist bekannt, dass es eine Facebook Gruppe gibt, jedoch bin ich strickter Social Media Gegner :/

Danke, lg

**Comment by Skudderon** [comment]
Hallo,
der Arduino Nano wird durch Estlcam mit der entsprechenden Firmware geflasht.
Der Ordner ist für spätere (optionale) Firmware für den Attiny gedacht.

... eine Information die im Social Media bekannt ist ;)

VG
der Admin der Facebook Gruppe

**Comment by isjo-org** [comment]
Danke!
