### ISSUE TITLE
Trinamic Schrittmotortreiber

### ISSUE THREAD

**Issue by Kriegel** [tnn85/MPCNC-Nano-Estlcam-Shield#4]
Hallo!

Ersmal Danke SEHR für dieses Open Board!

Ich werde Facebook auch nicht nutzen und wage es meine Frage nun hier zu stellen.
Ich bin auch totaler newbee in sachen Elektronik und CNC.
 
Die Trinamic Treiber TMC2100, TMC2130 und TMC2208 werden in der GRBL Szene als Goldstandard bezeichnet.
Da diese die Stepper sehr leise betreiben sollen.

Siehe hier ein der übersicht über GRBL Schrittmotortreiber:
[https://www.filamentpreis.de/alles-ueber-schrittmotor-treiber/](https://www.filamentpreis.de/alles-ueber-schrittmotor-treiber/)

Laut Trinamic haben die Chips eine "Stallguard" Technologie.

Was ist Stallguard??
Video:
[https://www.youtube.com/watch?v=Prw7wNa20Gk](https://www.youtube.com/watch?v=Prw7wNa20Gk)
Infos:
[https://www.trinamic.com/technology/adv-technologies/](https://www.trinamic.com/technology/adv-technologies/)

Die Stallguard Technologie soll ähnlich wie Closed Loop funktionieren UND soll die Endschalter unnötig machen UND die Referenzfahrt ermöglichen.
Das ergibt auch Kostenersparnis....

Vergleich von Trinamic Chips und features siehe hier:
[https://learn.watterott.com/silentstepstick/comparison/](https://learn.watterott.com/silentstepstick/comparison/)

Nun meine Frage(n):
Könnte das Board die Trinamic Chips nutzen?
 z.B. auch den TMC2280 ohne Stallguard

Könnte das Board oder Estlcam Stallguard unterstützen?

Danke im Vorraus

Trinamic ist  eine deutsche Firma, wie geil ....

**Comment by duke2421** [comment]
Moin, jain. Die Trinamics werden per SPI oder UART angesteuert, Auf diesem Board laufen werden sie, aber ohne die SPI/UART Verbindung zwischen µC und Treiber. Außerdem sind die im Stealth Chop Betrieb zwar leise haben aber weniger Kraft. Daher würde ich diese für meine Fräse eher nicht verwenden, da ist der Fräsmotor doch wesentlich lauter ;) 
Am 3D-Drucker sind sie aber top.

**Comment by tnn85** [comment]
Hallo @Kriegel 

erstmal danke für die Blumen ;)
Ich war am Anfang der Entwicklung der Platine auch noch recht unerfahren was das Thema angeht und welche Treiber es gibt.
Soweit mir bekannt gibt es 3 verschiedene "Wege" die Schrittmotortreiber von der Steuerung aus anzusprechen:
1) Standalone (DIR/STEP-Signale, Jumper für Mikrostep-Einstellung)
2) UART (eine serielle Schnittstelle, die auch die Grundlage von der seriellen Schnittstelle bei PCs ist und auch einen Rückkanal und Parametrierung (z.b. Mikrosteps) zulässt)
3) SPI (eine andere serielle Schnittstelle, die oft auf Platinen zu finden ist mit den gleichen Vorteilen wie UART

Ich hab mich trotz der Fokussierung der Community auf die DRV8825-Treiber auch mit anderen Treibern beschäftigt und bin auch schnell auf die Trinamic-Treiber gestoßen, die mit ihren zahlreichen Funktionen tatsächlich sehr verlockend wirken.

Da die eigentlich Firmware von Estlcam  aber (zumindest aktuell) "Closed Source" ist, also ich daran nichts ändern konnte/kann, kann hätte ich ohne zusätzliche Mikrocontroller auf der Platine diese Funktion des "stallGuard" gar nicht unterstützen können. Im Übrigen bietet der Treiber TMC2208 diese Funktion gar nicht an, sondern der TMC2209.
Die zweite nice to have-Funktion des "stealthChop", die @duke2421 meint und die ein bisschen weniger Drehmoment in Kauf nehmend die Motoren wesentlich leiser verfahren lässt,  bringt bei einer lauten CNC-Fräse auch recht wenig (höchstens beim Lasern, was aber meist relativ gesehen recht schnell vonstatten geht).

Klar wäre "sensorless Homing" eine tolle Funktion. Diese macht aber bei einem 3D-Drucker noch mehr sinn, als bei einer CNC-Fräse, bei der es auch ein bisschen ruppiger zugeht und es somit schwer wäre eine Endposition von einem ins Material eintauchen/einfräsen zu unterscheiden, bei dem der Widerstand auch höher als bei dem normalen Vorschub sein kann.

Beim CNC-Fräsen ist meist die absolute Position auch gar nicht so entscheidend, sondern eher das Werkstückkoordinantensystem.

**Comment by Kriegel** [comment]
Ja,  "sensorless Homing" z.B  im Eilgang währe auch Kontraproduktiv ... *LOL*

Danke euch Sehr für die erhellenden Ausführungen und eure Zeit.

Bleibt gesund!
