### ISSUE TITLE
GRBL support

### ISSUE THREAD

**Issue by derappelt** [tnn85/MPCNC-Nano-Estlcam-Shield#5]
In der Readme steht:
 (GRBL oder andere Firmware kann nach entsprechender Konfiguration auch mit der Platine verwendet werden)

Gibt es dazu mehr Details, wie eine entsprechende Konfiguration aussieht?

**Comment by duke2421** [comment]
Wenn Du Estlcam schon hast, kannst Du Dir mein Video ansehen um GRBL auf dieses Board zu bekommen: https://www.youtube.com/watch?v=5jDialYKdVM

Ansonsten https://github.com/duke2421/grbl

**Comment by derappelt** [comment]
Perfekt vielen Dank!
