### ISSUE TITLE
Bestellung des Shields

### ISSUE THREAD

**Issue by Holzhacker71** [tnn85/MPCNC-Nano-Estlcam-Shield#7]
Hallo ich wollte mal nachfragen ob noch Bausätze giebt?
Und ob mann die Platiene auch fertig bestückt erwerbenkann?

**Comment by tnn85** [comment]
Hallo, verspätete Antwort aber für andere möglicherweise interessant:
Ich habe keine Bausätze mehr und vertreibe die selbst auch schon lange nicht mehr. 
Es gab zwischen mir und @Skudderon eine Vereinbarung, dass er die Dinger vertreibt. Möglich, dass er noch Restbestände hat. 
Ich bin raus.
